services:
  agixt:
    image: joshxt/agixt:main
    init: true
    environment:
      DATABASE_TYPE: ${DATABASE_TYPE:-sqlite}
      DATABASE_NAME: ${DATABASE_NAME:-models/agixt}
      UVICORN_WORKERS: ${UVICORN_WORKERS:-10}
      AGIXT_API_KEY: ${AGIXT_API_KEY:-None}
      AGIXT_URI: ${AGIXT_URI:-http://agixt:7437}
      AUTH_PROVIDER: ${AUTH_PROVIDER:-magicalauth}
      MAGIC_LINK_URL: ${AUTH_WEB:-http://localhost:3437/user}
      DISABLED_EXTENSIONS: ${DISABLED_EXTENSIONS}
      DISABLED_PROVIDERS: ${DISABLED_PROVIDERS}
      WORKING_DIRECTORY: ${WORKING_DIRECTORY:-/agixt/WORKSPACE}
      REGISTRATION_DISABLED: ${REGISTRATION_DISABLED:-false}
      TOKENIZERS_PARALLELISM: "false"
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      AWS_CLIENT_ID: ${AWS_CLIENT_ID}
      AWS_CLIENT_SECRET: ${AWS_CLIENT_SECRET}
      AWS_REGION: ${AWS_REGION}
      AWS_USER_POOL_ID: ${AWS_USER_POOL_ID}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      MICROSOFT_CLIENT_ID: ${MICROSOFT_CLIENT_ID}
      MICROSOFT_CLIENT_SECRET: ${MICROSOFT_CLIENT_SECRET}
      TZ: ${TZ:-America/New_York}
    ports:
      - "${AGIXT_PORT:-7437}:7437"
    volumes:
      - ./models:/agixt/models
      - ./WORKSPACE:/agixt/WORKSPACE
      - ./agixt/agents:/agixt/agents
      - ./agixt/prompts:/agixt/prompts
      - ./agixt/chains:/agixt/chains
      - ./agixt/memories:/agixt/memories
      - ./agixt/registration_requirements.json:/agixt/registration_requirements.json
      - /var/run/docker.sock:/var/run/docker.sock
  agixtinteractive:
    image: joshxt/agixt-interactive:main
    init: true
    environment:
      NEXT_TELEMETRY_DISABLED: 1
      AGIXT_AGENT: ${AGIXT_AGENT:-gpt4free}
      AGIXT_FILE_UPLOAD_ENABLED: ${AGIXT_FILE_UPLOAD_ENABLED:-true}
      AGIXT_VOICE_INPUT_ENABLED: ${AGIXT_VOICE_INPUT_ENABLED:-true}
      AGIXT_FOOTER_MESSAGE: ${AGIXT_FOOTER_MESSAGE:-Powered by AGiXT}
      AGIXT_REQUIRE_API_KEY: ${AGIXT_REQUIRE_API_KEY:-false}
      AGIXT_RLHF: ${AGIXT_RLHF:-true}
      AGIXT_ALLOW_MESSAGE_EDITING: ${AGIXT_ALLOW_MESSAGE_EDITING:-true}
      AGIXT_ALLOW_MESSAGE_DELETION: ${AGIXT_ALLOW_MESSAGE_DELETION:-true}
      AGIXT_SHOW_OVERRIDE_SWITCHES: ${AGIXT_SHOW_OVERRIDE_SWITCHES:-tts,websearch,analyze-user-input}
      AGIXT_SHOW_CHAT_THEME_TOGGLES: ${AGIXT_SHOW_CHAT_THEME_TOGGLES}
      AGIXT_SERVER: ${AGIXT_URI:-http://localhost:7437}
      AGIXT_SHOW_AGENT_BAR: ${AGIXT_SHOW_AGENT_BAR:-true}
      AGIXT_SHOW_APP_BAR: ${AGIXT_SHOW_APP_BAR:-true}
      AGIXT_SHOW_SELECTION: ${AGIXT_SHOW_SELECTION:-conversation,agent}
      AGIXT_CONVERSATION_MODE: ${AGIXT_CONVERSATION_MODE:-select}
      APP_DESCRIPTION: ${APP_DESCRIPTION:-A chat powered by AGiXT.}
      INTERACTIVE_MODE: ${INTERACTIVE_MODE:-chat}
      APP_NAME: ${APP_NAME:-AGiXT}
      APP_URI: ${APP_URI:-http://localhost:3437}
      AUTH_WEB: ${AUTH_WEB:-http://localhost:3437/user}
      LOG_VERBOSITY_SERVER: 3
      THEME_NAME: ${THEME_NAME}
      ALLOW_EMAIL_SIGN_IN: ${ALLOW_EMAIL_SIGN_IN:-true}
      AOL_CLIENT_ID: ${AOL_CLIENT_ID}
      APPLE_CLIENT_ID: ${APPLE_CLIENT_ID}
      AUTODESK_CLIENT_ID: ${AUTODESK_CLIENT_ID}
      AWS_CLIENT_ID: ${AWS_CLIENT_ID}
      AWS_REGION: ${AWS_REGION}
      AWS_USER_POOL_ID: ${AWS_USER_POOL_ID}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      MICROSOFT_CLIENT_ID: ${MICROSOFT_CLIENT_ID}
      TZ: ${TZ:-America/New_York}
    ports:
      - "${AGIXT_INTERACTIVE_PORT:-3437}:3437"
    restart: unless-stopped
    volumes:
      - ./node_modules:/app/node_modules
