services:
  agixt:
    image: joshxt/agixt:main
    init: true
    environment:
      DATABASE_TYPE: ${DATABASE_TYPE:-sqlite}
      DATABASE_NAME: ${DATABASE_NAME:-models/agixt}
      UVICORN_WORKERS: ${UVICORN_WORKERS:-10}
      AGIXT_API_KEY: ${AGIXT_API_KEY:-None}
      AGIXT_URI: ${AGIXT_URI:-http://agixt:7437}
      AUTH_PROVIDER: ${AUTH_PROVIDER:-magicalauth}
      MAGIC_LINK_URL: ${AUTH_WEB:-http://localhost:3437/user}
      DISABLED_EXTENSIONS: ${DISABLED_EXTENSIONS}
      DISABLED_PROVIDERS: ${DISABLED_PROVIDERS}
      WORKING_DIRECTORY: ${WORKING_DIRECTORY:-/agixt/WORKSPACE}
      REGISTRATION_DISABLED: ${REGISTRATION_DISABLED:-false}
      TOKENIZERS_PARALLELISM: False
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      AOL_CLIENT_ID: ${AOL_CLIENT_ID}
      AOL_CLIENT_SECRET: ${AOL_CLIENT_SECRET}
      APPLE_CLIENT_ID: ${APPLE_CLIENT_ID}
      APPLE_CLIENT_SECRET: ${APPLE_CLIENT_SECRET}
      AUTODESK_CLIENT_ID: ${AUTODESK_CLIENT_ID}
      AUTODESK_CLIENT_SECRET: ${AUTODESK_CLIENT_SECRET}
      AWS_CLIENT_ID: ${AWS_CLIENT_ID}
      AWS_CLIENT_SECRET: ${AWS_CLIENT_SECRET}
      AWS_REGION: ${AWS_REGION}
      AWS_USER_POOL_ID: ${AWS_USER_POOL_ID}
      BATTLENET_CLIENT_ID: ${BATTLENET_CLIENT_ID}
      BATTLENET_CLIENT_SECRET: ${BATTLENET_CLIENT_SECRET}
      BITBUCKET_CLIENT_ID: ${BITBUCKET_CLIENT_ID}
      BITBUCKET_CLIENT_SECRET: ${BITBUCKET_CLIENT_SECRET}
      BITLY_ACCESS_TOKEN: ${BITLY_ACCESS_TOKEN}
      BITLY_CLIENT_ID: ${BITLY_CLIENT_ID}
      BITLY_CLIENT_SECRET: ${BITLY_CLIENT_SECRET}
      CF_CLIENT_ID: ${CF_CLIENT_ID}
      CF_CLIENT_SECRET: ${CF_CLIENT_SECRET}
      CLEAR_SCORE_CLIENT_ID: ${CLEAR_SCORE_CLIENT_ID}
      CLEAR_SCORE_CLIENT_SECRET: ${CLEAR_SCORE_CLIENT_SECRET}
      DEUTSCHE_TELKOM_CLIENT_ID: ${DEUTSCHE_TELKOM_CLIENT_ID}
      DEUTSCHE_TELKOM_CLIENT_SECRET: ${DEUTSCHE_TELKOM_CLIENT_SECRET}
      DEVIANTART_CLIENT_ID: ${DEVIANTART_CLIENT_ID}
      DEVIANTART_CLIENT_SECRET: ${DEVIANTART_CLIENT_SECRET}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DROPBOX_CLIENT_ID: ${DROPBOX_CLIENT_ID}
      DROPBOX_CLIENT_SECRET: ${DROPBOX_CLIENT_SECRET}
      FACEBOOK_CLIENT_ID: ${FACEBOOK_CLIENT_ID}
      FACEBOOK_CLIENT_SECRET: ${FACEBOOK_CLIENT_SECRET}
      FATSECRET_CLIENT_ID: ${FATSECRET_CLIENT_ID}
      FATSECRET_CLIENT_SECRET: ${FATSECRET_CLIENT_SECRET}
      FITBIT_CLIENT_ID: ${FITBIT_CLIENT_ID}
      FITBIT_CLIENT_SECRET: ${FITBIT_CLIENT_SECRET}
      FORMSTACK_CLIENT_ID: ${FORMSTACK_CLIENT_ID}
      FORMSTACK_CLIENT_SECRET: ${FORMSTACK_CLIENT_SECRET}
      FOURSQUARE_CLIENT_ID: ${FOURSQUARE_CLIENT_ID}
      FOURSQUARE_CLIENT_SECRET: ${FOURSQUARE_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GITLAB_CLIENT_ID: ${GITLAB_CLIENT_ID}
      GITLAB_CLIENT_SECRET: ${GITLAB_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      HUDDLE_CLIENT_ID: ${HUDDLE_CLIENT_ID}
      HUDDLE_CLIENT_SECRET: ${HUDDLE_CLIENT_SECRET}
      IMGUR_CLIENT_ID: ${IMGUR_CLIENT_ID}
      IMGUR_CLIENT_SECRET: ${IMGUR_CLIENT_SECRET}
      INSTAGRAM_CLIENT_ID: ${INSTAGRAM_CLIENT_ID}
      INSTAGRAM_CLIENT_SECRET: ${INSTAGRAM_CLIENT_SECRET}
      INTEL_CLIENT_ID: ${INTEL_CLIENT_ID}
      INTEL_CLIENT_SECRET: ${INTEL_CLIENT_SECRET}
      JIVE_CLIENT_ID: ${JIVE_CLIENT_ID}
      JIVE_CLIENT_SECRET: ${JIVE_CLIENT_SECRET}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL}
      LINKEDIN_CLIENT_ID: ${LINKEDIN_CLIENT_ID}
      LINKEDIN_CLIENT_SECRET: ${LINKEDIN_CLIENT_SECRET}
      MICROSOFT_CLIENT_ID: ${MICROSOFT_CLIENT_ID}
      MICROSOFT_CLIENT_SECRET: ${MICROSOFT_CLIENT_SECRET}
      NETIQ_CLIENT_ID: ${NETIQ_CLIENT_ID}
      NETIQ_CLIENT_SECRET: ${NETIQ_CLIENT_SECRET}
      OKTA_CLIENT_ID: ${OKTA_CLIENT_ID}
      OKTA_CLIENT_SECRET: ${OKTA_CLIENT_SECRET}
      OKTA_DOMAIN: ${OKTA_DOMAIN}
      OPENAM_BASE_URL: ${OPENAM_BASE_URL}
      OPENAM_CLIENT_ID: ${OPENAM_CLIENT_ID}
      OPENAM_CLIENT_SECRET: ${OPENAM_CLIENT_SECRET}
      ORCID_CLIENT_ID: ${ORCID_CLIENT_ID}
      ORCID_CLIENT_SECRET: ${ORCID_CLIENT_SECRET}
      OSM_CLIENT_ID: ${OSM_CLIENT_ID}
      OSM_CLIENT_SECRET: ${OSM_CLIENT_SECRET}
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PAYPAL_CLIENT_SECRET: ${PAYPAL_CLIENT_SECRET}
      PING_IDENTITY_CLIENT_ID: ${PING_IDENTITY_CLIENT_ID}
      PING_IDENTITY_CLIENT_SECRET: ${PING_IDENTITY_CLIENT_SECRET}
      PIXIV_CLIENT_ID: ${PIXIV_CLIENT_ID}
      PIXIV_CLIENT_SECRET: ${PIXIV_CLIENT_SECRET}
      REDDIT_CLIENT_ID: ${REDDIT_CLIENT_ID}
      REDDIT_CLIENT_SECRET: ${REDDIT_CLIENT_SECRET}
      SALESFORCE_CLIENT_ID: ${SALESFORCE_CLIENT_ID}
      SALESFORCE_CLIENT_SECRET: ${SALESFORCE_CLIENT_SECRET}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      STACKEXCHANGE_CLIENT_ID: ${STACKEXCHANGE_CLIENT_ID}
      STACKEXCHANGE_CLIENT_SECRET: ${STACKEXCHANGE_CLIENT_SECRET}
      STRAVA_CLIENT_ID: ${STRAVA_CLIENT_ID}
      STRAVA_CLIENT_SECRET: ${STRAVA_CLIENT_SECRET}
      STRIPE_CLIENT_ID: ${STRIPE_CLIENT_ID}
      STRIPE_CLIENT_SECRET: ${STRIPE_CLIENT_SECRET}
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET}
      VIADEO_CLIENT_ID: ${VIADEO_CLIENT_ID}
      VIADEO_CLIENT_SECRET: ${VIADEO_CLIENT_SECRET}
      VIMEO_CLIENT_ID: ${VIMEO_CLIENT_ID}
      VIMEO_CLIENT_SECRET: ${VIMEO_CLIENT_SECRET}
      VK_CLIENT_ID: ${VK_CLIENT_ID}
      VK_CLIENT_SECRET: ${VK_CLIENT_SECRET}
      WECHAT_CLIENT_ID: ${WECHAT_CLIENT_ID}
      WECHAT_CLIENT_SECRET: ${WECHAT_CLIENT_SECRET}
      WEIBO_CLIENT_ID: ${WEIBO_CLIENT_ID}
      WEIBO_CLIENT_SECRET: ${WEIBO_CLIENT_SECRET}
      WITHINGS_CLIENT_ID: ${WITHINGS_CLIENT_ID}
      WITHINGS_CLIENT_SECRET: ${WITHINGS_CLIENT_SECRET}
      XERO_CLIENT_ID: ${XERO_CLIENT_ID}
      XERO_CLIENT_SECRET: ${XERO_CLIENT_SECRET}
      XING_CLIENT_ID: ${XING_CLIENT_ID}
      XING_CLIENT_SECRET: ${XING_CLIENT_SECRET}
      YAHOO_CLIENT_ID: ${YAHOO_CLIENT_ID}
      YAHOO_CLIENT_SECRET: ${YAHOO_CLIENT_SECRET}
      YAMMER_CLIENT_ID: ${YAMMER_CLIENT_ID}
      YAMMER_CLIENT_SECRET: ${YAMMER_CLIENT_SECRET}
      YANDEX_CLIENT_ID: ${YANDEX_CLIENT_ID}
      YANDEX_CLIENT_SECRET: ${YANDEX_CLIENT_SECRET}
      YELP_CLIENT_ID: ${YELP_CLIENT_ID}
      YELP_CLIENT_SECRET: ${YELP_CLIENT_SECRET}
      ZENDESK_CLIENT_ID: ${ZENDESK_CLIENT_ID}
      ZENDESK_CLIENT_SECRET: ${ZENDESK_CLIENT_SECRET}
      ZENDESK_SUBDOMAIN: ${ZENDESK_SUBDOMAIN}
      TZ: ${TZ:-America/New_York}
    ports:
      - 7437:7437
    volumes:
      - ./models:/agixt/models
      - ./agixt/WORKSPACE:/agixt/WORKSPACE
      - ./agixt/agents:/agixt/agents
      - ./agixt/prompts:/agixt/prompts
      - ./agixt/chains:/agixt/chains
      - ./agixt/memories:/agixt/memories
      - ./agixt/registration_requirements.json:/agixt/registration_requirements.json
      - /var/run/docker.sock:/var/run/docker.sock
  agixtinteractive:
    image: joshxt/agixt-interactive:main
    init: true
    environment:
      NEXT_TELEMETRY_DISABLED: 1
      AGIXT_AGENT: ${AGIXT_AGENT:-gpt4free}
      AGIXT_FILE_UPLOAD_ENABLED: ${AGIXT_FILE_UPLOAD_ENABLED:-true}
      AGIXT_VOICE_INPUT_ENABLED: ${AGIXT_VOICE_INPUT_ENABLED:-true}
      AGIXT_FOOTER_MESSAGE: ${AGIXT_FOOTER_MESSAGE:-Powered by AGiXT}
      AGIXT_REQUIRE_API_KEY: ${AGIXT_REQUIRE_API_KEY:-false}
      AGIXT_RLHF: ${AGIXT_RLHF:-true}
      AGIXT_SERVER: http://localhost:7437
      AGIXT_SHOW_AGENT_BAR: ${AGIXT_SHOW_AGENT_BAR:-true}
      AGIXT_SHOW_APP_BAR: ${AGIXT_SHOW_APP_BAR:-true}
      AGIXT_SHOW_SELECTION: ${AGIXT_SHOW_SELECTION:-conversation,agent}
      AGIXT_CONVERSATION_MODE: ${AGIXT_CONVERSATION_MODE:-select}
      APP_DESCRIPTION: ${APP_DESCRIPTION:-A chat powered by AGiXT.}
      INTERACTIVE_MODE: ${INTERACTIVE_MODE:-chat}
      APP_NAME: ${APP_NAME:-AGiXT}
      APP_URI: ${APP_URI:-http://localhost:3437}
      AUTH_WEB: ${AUTH_WEB:-http://localhost:3437/user}
      LOG_VERBOSITY_SERVER: 3
      THEME_NAME: ${THEME_NAME}
      ALLOW_EMAIL_SIGN_IN: ${ALLOW_EMAIL_SIGN_IN:-true}
      AOL_CLIENT_ID: ${AOL_CLIENT_ID}
      APPLE_CLIENT_ID: ${APPLE_CLIENT_ID}
      AUTODESK_CLIENT_ID: ${AUTODESK_CLIENT_ID}
      AWS_CLIENT_ID: ${AWS_CLIENT_ID}
      AWS_REGION: ${AWS_REGION}
      AWS_USER_POOL_ID: ${AWS_USER_POOL_ID}
      BATTLENET_CLIENT_ID: ${BATTLENET_CLIENT_ID}
      BITBUCKET_CLIENT_ID: ${BITBUCKET_CLIENT_ID}
      BITLY_ACCESS_TOKEN: ${BITLY_ACCESS_TOKEN}
      BITLY_CLIENT_ID: ${BITLY_CLIENT_ID}
      CF_CLIENT_ID: ${CF_CLIENT_ID}
      CLEAR_SCORE_CLIENT_ID: ${CLEAR_SCORE_CLIENT_ID}
      DEUTSCHE_TELKOM_CLIENT_ID: ${DEUTSCHE_TELKOM_CLIENT_ID}
      DEVIANTART_CLIENT_ID: ${DEVIANTART_CLIENT_ID}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DROPBOX_CLIENT_ID: ${DROPBOX_CLIENT_ID}
      FACEBOOK_CLIENT_ID: ${FACEBOOK_CLIENT_ID}
      FATSECRET_CLIENT_ID: ${FATSECRET_CLIENT_ID}
      FITBIT_CLIENT_ID: ${FITBIT_CLIENT_ID}
      FORMSTACK_CLIENT_ID: ${FORMSTACK_CLIENT_ID}
      FOURSQUARE_CLIENT_ID: ${FOURSQUARE_CLIENT_ID}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITLAB_CLIENT_ID: ${GITLAB_CLIENT_ID}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      HUDDLE_CLIENT_ID: ${HUDDLE_CLIENT_ID}
      IMGUR_CLIENT_ID: ${IMGUR_CLIENT_ID}
      INSTAGRAM_CLIENT_ID: ${INSTAGRAM_CLIENT_ID}
      INTEL_CLIENT_ID: ${INTEL_CLIENT_ID}
      JIVE_CLIENT_ID: ${JIVE_CLIENT_ID}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL}
      LINKEDIN_CLIENT_ID: ${LINKEDIN_CLIENT_ID}
      MICROSOFT_CLIENT_ID: ${MICROSOFT_CLIENT_ID}
      NETIQ_CLIENT_ID: ${NETIQ_CLIENT_ID}
      OKTA_CLIENT_ID: ${OKTA_CLIENT_ID}
      OKTA_DOMAIN: ${OKTA_DOMAIN}
      OPENAM_BASE_URL: ${OPENAM_BASE_URL}
      OPENAM_CLIENT_ID: ${OPENAM_CLIENT_ID}
      ORCID_CLIENT_ID: ${ORCID_CLIENT_ID}
      OSM_CLIENT_ID: ${OSM_CLIENT_ID}
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PING_IDENTITY_CLIENT_ID: ${PING_IDENTITY_CLIENT_ID}
      PIXIV_CLIENT_ID: ${PIXIV_CLIENT_ID}
      REDDIT_CLIENT_ID: ${REDDIT_CLIENT_ID}
      SALESFORCE_CLIENT_ID: ${SALESFORCE_CLIENT_ID}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      STACKEXCHANGE_CLIENT_ID: ${STACKEXCHANGE_CLIENT_ID}
      STRAVA_CLIENT_ID: ${STRAVA_CLIENT_ID}
      STRIPE_CLIENT_ID: ${STRIPE_CLIENT_ID}
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      VIADEO_CLIENT_ID: ${VIADEO_CLIENT_ID}
      VIMEO_CLIENT_ID: ${VIMEO_CLIENT_ID}
      VK_CLIENT_ID: ${VK_CLIENT_ID}
      WECHAT_CLIENT_ID: ${WECHAT_CLIENT_ID}
      WEIBO_CLIENT_ID: ${WEIBO_CLIENT_ID}
      WITHINGS_CLIENT_ID: ${WITHINGS_CLIENT_ID}
      XERO_CLIENT_ID: ${XERO_CLIENT_ID}
      XING_CLIENT_ID: ${XING_CLIENT_ID}
      YAHOO_CLIENT_ID: ${YAHOO_CLIENT_ID}
      YAMMER_CLIENT_ID: ${YAMMER_CLIENT_ID}
      YANDEX_CLIENT_ID: ${YANDEX_CLIENT_ID}
      YELP_CLIENT_ID: ${YELP_CLIENT_ID}
      ZENDESK_CLIENT_ID: ${ZENDESK_CLIENT_ID}
      ZENDESK_SUBDOMAIN: ${ZENDESK_SUBDOMAIN}
      TZ: ${TZ:-America/New_York}
    ports:
      - 3437:3437
    restart: unless-stopped
    volumes:
      - ./node_modules:/app/node_modules
