blank_issues_enabled: true
contact_links:
  - name: Discuss the Project in Discord
    url: https://discord.gg/R4tqghAgSE
    about: Ask questions and discuss with other community members.
  - name: Write Us an E-Mail
    url: mailto:contact@AGiXT.com
    about: Sponsorship, Media, and other topics not related to troublshooting, bug reports or feature requests.
